"""make_user_id_nullable_and_add_visitor_id

Revision ID: 9ecec3fb6139
Revises: e1b2c3d4e5f6
Create Date: 2026-01-16 21:03:15.747708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ecec3fb6139'
down_revision: Union[str, None] = 'e1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'smtp_config' not in tables:
        op.create_table('smtp_config',
            sa.Column('id', sa.String(length=36), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('provider', sa.String(length=50), nullable=False),
            sa.Column('smtp_host', sa.String(length=200), nullable=False),
            sa.Column('smtp_port', sa.Integer(), nullable=False),
            sa.Column('smtp_encryption', sa.String(length=20), nullable=False),
            sa.Column('smtp_user', sa.String(length=200), nullable=True),
            sa.Column('smtp_password', sa.String(length=500), nullable=True),
            sa.Column('from_email', sa.String(length=200), nullable=True),
            sa.Column('from_name', sa.String(length=100), nullable=False),
            sa.Column('reply_to', sa.String(length=200), nullable=True),
            sa.Column('api_key', sa.String(length=500), nullable=True),
            sa.Column('api_url', sa.String(length=500), nullable=True),
            sa.Column('is_enabled', sa.Boolean(), nullable=False),
            sa.Column('is_default', sa.Boolean(), nullable=False),
            sa.Column('daily_limit', sa.Integer(), nullable=True),
            sa.Column('hourly_limit', sa.Integer(), nullable=True),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )

    columns = [c['name'] for c in inspector.get_columns('conversations')]
    if 'visitor_id' not in columns:
        op.add_column('conversations', sa.Column('visitor_id', sa.String(length=36), nullable=True))
        op.create_index(op.f('ix_conversations_visitor_id'), 'conversations', ['visitor_id'], unique=False)
    
    op.alter_column('conversations', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_visitor_id'), table_name='conversations')
    op.alter_column('conversations', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('conversations', 'visitor_id')
    op.drop_table('smtp_config')
    # ### end Alembic commands ###
