"""add_model_specific_credits_to_redeem_codes_and_users

Revision ID: aa4369aa85f0
Revises: 
Create Date: 2026-01-10 04:25:10.821803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa4369aa85f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加兑换码表的新字段，默认值为 0
    op.add_column('redeem_codes', sa.Column('pro3_credits', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('redeem_codes', sa.Column('flash_credits', sa.Integer(), nullable=False, server_default='0'))
    # 添加用户表的新字段，默认值为 0
    op.add_column('users', sa.Column('pro3_balance', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('flash_balance', sa.Integer(), nullable=False, server_default='0'))
    # 修改 note 字段类型
    op.alter_column('users', 'note',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'note',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('users', 'flash_balance')
    op.drop_column('users', 'pro3_balance')
    op.drop_column('redeem_codes', 'flash_credits')
    op.drop_column('redeem_codes', 'pro3_credits')
    # ### end Alembic commands ###
