"""Add user_feedback, queue_metrics, queue_alert tables

Revision ID: c38e8d05444c
Revises: 2f7c74e8c8d3
Create Date: 2026-01-22 18:28:19.137550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c38e8d05444c'
down_revision: Union[str, None] = '2f7c74e8c8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_visitors_custom_endpoint', table_name='visitors')
    op.drop_index('ix_visitors_visitor_id', table_name='visitors')
    op.drop_table('visitors')
    op.alter_column('queue_alerts', 'current_value',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('queue_alerts', 'threshold_value',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queue_alerts', 'threshold_value',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('queue_alerts', 'current_value',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_table('visitors',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('visitor_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('custom_endpoint', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('conversation_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='visitors_pkey')
    )
    op.create_index('ix_visitors_visitor_id', 'visitors', ['visitor_id'], unique=True)
    op.create_index('ix_visitors_custom_endpoint', 'visitors', ['custom_endpoint'], unique=False)
    # ### end Alembic commands ###
